app:
  config:
    auth:
      username: ${SPRING_SECURITY_USER_NAME:interviewUser}
      password: ${SPRING_SECURITY_USER_PASSWORD:reallyNotSafePassword}
      role: ${SPRING_SECURITY_USER_ROLE:admin}

server:
  port: 8080
spring:
  application:
    name: sensitive-words-service
  cloud:
    vault:
      enabled: true
      uri: http://localhost:8200
      token: ${VAULT_AUTH_ROOT_TOKEN:vault-plaintext-root-token}
      kv:
        enabled: true
        backend: secret
        default-context: application
  config:
    import: vault://
  docker:
    compose:
      enabled: true
      file: compose.yaml
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html